export const Headphones = [
  {
    id: 1,
    group: 1,
    img: './assets/images/Image1.png',
    title: 'Apple BYZ S852I',
    price: '2927',
    rate: '4.7',
    isInCart: false,
    isInFavorites: false,
  },
  {
    id: 2,
    group: 1,
    img: './assets/images/Image2.png',
    title: 'Apple EarPods',
    price: '2327',
    rate: '4.5',
    isInCart: false,
    isInFavorites: false,
  },
  {
    id: 3,
    group: 1,
    img: './assets/images/Image3.png',
    title: 'Apple EarPods',
    price: '2327',
    rate: '4.5',
    isInCart: false,
    isInFavorites: false,
  },
  {
    id: 4,
    group: 1,
    img: './assets/images/Image1.png',
    title: 'Apple BYZ S852I',
    price: '2927',
    rate: '4.7',
    isInCart: false,
    isInFavorites: false,
  },
  {
    id: 5,
    group: 1,
    img: './assets/images/Image2.png',
    title: 'Apple EarPods',
    price: '2327',
    rate: '4.5',
    isInCart: false,
    isInFavorites: false,
  },
  {
    id: 6,
    group: 1,
    img: './assets/images/Image3.png',
    title: 'Apple EarPods',
    price: '2327',
    rate: '4.5',
    isInCart: false,
    isInFavorites: false,
  },
  {
    id: 7,
    group: 2,
    img: './assets/images/Image7.png',
    title: 'Apple AirPods',
    price: '9527',
    rate: '4.7',
    isInCart: false,
    isInFavorites: false,
  },
  {
    id: 8,
    group: 2,
    img: './assets/images/Image8.png',
    title: 'GERLAX GH-04',
    price: '6527',
    rate: '4.7',
    isInCart: false,
    isInFavorites: false,
  },
  {
    id: 9,
    group: 2,
    img: './assets/images/Image9.png',
    title: 'BOROFONE BO4',
    price: '7527',
    rate: '4.7',
    isInCart: false,
    isInFavorites: false,
  },
];
