export const Headphones = [
  {
    id: 1,
    img: './assets/images/Image1.png',
    title: 'Apple BYZ S852I',
    price: '2927',
    rate: '4.7',
    isInCart: false,
    isInFavorites: false,
  },
  {
    id: 2,
    img: './assets/images/Image2.png',
    title: 'Apple EarPods',
    price: '2327',
    rate: '4.5',
    isInCart: false,
    isInFavorites: false,
  },
  {
    id: 3,
    img: './assets/images/Image3.png',
    title: 'Apple EarPods',
    price: '2327',
    rate: '4.5',
    isInCart: false,
    isInFavorites: false,
  },
  {
    id: 4,
    img: './assets/images/Image4.png',
    title: 'Apple BYZ S852I',
    price: '2927',
    rate: '4.7',
    isInCart: false,
    isInFavorites: false,
  },
  {
    id: 5,
    img: './assets/images/Image5.png',
    title: 'Apple EarPods',
    price: '2327',
    rate: '4.5',
    isInCart: false,
    isInFavorites: false,
  },
  {
    id: 6,
    img: './assets/images/Image6.png',
    title: 'Apple EarPods',
    price: '2327',
    rate: '4.5',
    isInCart: false,
    isInFavorites: false,
  },
];

export const WirelessHeadphones = [
  {
    id: 1,
    img: './assets/images/Image7.png',
    title: 'Apple AirPods',
    price: '9527',
    rate: '4.7',
    isInCart: false,
    isInFavorites: false,
  },
  {
    id: 2,
    img: './assets/images/Image8.png',
    title: 'GERLAX GH-04',
    price: '6527',
    rate: '4.7',
    isInCart: false,
    isInFavorites: false,
  },
  {
    id: 3,
    img: './assets/images/Image9.png',
    title: 'BOROFONE BO4',
    price: '7527',
    rate: '4.7',
    isInCart: false,
    isInFavorites: false,
  },
];
